name: Build Tray Service - Standalone (Manual)

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git reference for what to push
        default: master
        required: true
      filename:
        description: Name of the file to upload to shokoanime.com
        default: ShokoServer.zip
        required: true
      release:
        description: Release Channel
        default: dev
        required: true

jobs:
  tray-service-standalone-manual:
    runs-on: windows-latest

    strategy:
      matrix:
        dotnet: [ '8.x' ]

    name: Shoko Tray Service build

    steps:
      - name: Checkout branch
        uses: actions/checkout@master
        with:
          ref: "${{ github.event.inputs.ref }}"
          submodules: recursive
          fetch-depth: 0 # This is set to download the full git history for the repo

      - name: Replace Sentry DSN and other keys
        shell: pwsh
        run: |
          .\\.github\\workflows\\ReplaceSentryDSN.ps1 -dsn ${{ secrets.SENTRY_DSN }}
          .\\.github\\workflows\\ReplaceAVD3URL.ps1 -url ${{ secrets.AVD3_URL }}

      - name: Get release info
        id: release_info
        uses: revam/gh-action-get-tag-and-version@v1
        with:
          tag: "${{ github.event.inputs.ref }}"
          prefix: v
          prefixRegex: "[vV]?"

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - run: dotnet publish -c Release -r win-x64 --self-contained true -f net8.0-windows Shoko.TrayService /p:Version="${{ steps.release_info.outputs.version }}" /p:InformationalVersion="channel=${{ github.event.inputs.release }}%2ccommit=${{ github.sha }}%2cdate=${{ steps.release_info.outputs.date }}%2c" # %2c is comma, blame windows/pwsh

      - uses: actions/upload-artifact@v3
        with:
          name: Shoko.TrayService
          path: Shoko.Server/bin/Release/net8.0-windows/win-x64/publish/

      - name: Archive Release
        shell: pwsh
        run: Compress-Archive .\\Shoko.Server\\bin\\Release\\net8.0-windows\\win-x64\\publish .\\ShokoServer.zip

      - name: Upload Daily to shokoanime.com
        shell: pwsh
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
        run : .\\.github\\workflows\\UploadArchive.ps1 -filename "${{ github.event.inputs.filename }}"
